[site]
domain = "localhost"
port = "9090"

[log]
enableLog = 1
logPath = "/Users/liuyong/Documents/go/logs"

[mysql]
MaxIdleConns = 10 #空闲时最大的连接数
MaxOpenConns = 100 #最大的连接数
charset = "utf8"

[mysql.master]
host = "127.0.0.1"
port = "3306"
database = "kaquan"
user = "root"
password = "123"
charset = "utf8"

[mysql.slave]
host = "127.0.0.1"
port = "3306"
database = "kaquan"
user = "root"
password = "123"
charset = "utf8"

